-- Migration 026: Notifications table
-- Stores user notifications generated by FlexFlow engines
-- Supports: urgent alerts, info notifications, read/unread state

CREATE TABLE IF NOT EXISTS notifications (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  alert_type     VARCHAR(60)  NOT NULL,
  alert_subtype  VARCHAR(60),
  title          VARCHAR(200) NOT NULL,
  body           TEXT         NOT NULL,
  is_read        BOOLEAN      DEFAULT false,
  read_at        TIMESTAMPTZ,
  priority       VARCHAR(20)  DEFAULT 'info',  -- 'urgent' | 'info'
  metadata       JSONB        DEFAULT '{}',
  created_at     TIMESTAMPTZ  DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_notifications_user     ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_unread   ON notifications(user_id, is_read) WHERE is_read = false;
CREATE INDEX IF NOT EXISTS idx_notifications_created  ON notifications(created_at DESC);
